packages:
  - 'frontend'
  - 'backend'
allowBuilds:
  '@nestjs/core': true
  unrs-resolver: true
  sharp: true
  bcrypt: true
  '@prisma/engines': true
  prisma: true
  '@prisma/client': true
  msw: true
